packages:
  - frontend
  - backend
  - packages/*

catalog:
  typescript: ^5.9.3
  vite: npm:rolldown-vite@7.2.5

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
  - bcrypt
  - unrs-resolver
